-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO INFO JOIN ITEM_TREE TREE
ON INFO.ITEM_ID = TREE.ITEM_ID
WHERE INFO.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID = INFO.ITEM_ID)
ORDER BY ITEM_ID DESC;