-- 코드를 작성해주세요
SELECT ED.ID, IFNULL(CNT.CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN
(SELECT PARENT.ID AS ID, COUNT(PARENT.ID) AS CHILD_COUNT
FROM ECOLI_DATA CHILD JOIN ECOLI_DATA PARENT
WHERE CHILD.PARENT_ID = PARENT.ID
GROUP BY PARENT.ID) AS CNT
ON ED.ID = CNT.ID
ORDER BY ED.ID;